// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBL7hnaTELYsdCfIceIbQrob06wobdOYYY',
    appId: '1:312799945662:web:ca099b4d7ab924a2e2cfef',
    messagingSenderId: '312799945662',
    projectId: 'duos-fd03d',
    authDomain: 'duos-fd03d.firebaseapp.com',
    storageBucket: 'duos-fd03d.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBxLQdbV4y5k4GPs5ekrLMANtSUREeYltI',
    appId: '1:312799945662:android:73f4b2701101c9a8e2cfef',
    messagingSenderId: '312799945662',
    projectId: 'duos-fd03d',
    storageBucket: 'duos-fd03d.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDaDif92NKnVHJyhbx84ww0jUPeK02ufrE',
    appId: '1:312799945662:ios:551d95c442b9191ee2cfef',
    messagingSenderId: '312799945662',
    projectId: 'duos-fd03d',
    storageBucket: 'duos-fd03d.appspot.com',
    iosClientId: '312799945662-sfgv8mqiddu1cekufefb2rbceeivfk4a.apps.googleusercontent.com',
    iosBundleId: 'com.example.duosUi',
  );
}
